[project]
name = "make-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logfire",
    "pydantic-ai",
    "tiktoken",
    "python-telegram-bot",
    "python-dotenv",
    "anyio",
    "telegramify-markdown",
]
authors = [
    { name = "Ferdous", email = "ferdous@hey.com" }
]
keywords = ["investment", "finance", "trading", "agent", "mcp", "model context protocol", "broker", "tastytrade", "wallstreetbets"]
classifiers = [
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Office/Business :: Financial",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
]

[dependency-groups]
dev = [
    "ipykernel"
]
lint = [
    "ruff"
]

[project.scripts]
bot = "make_bot.run:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["make_bot"]
