[project]
name = "make-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=0.1.3",
    "pydantic-ai-slim[mcp]>=0.1.3",
    "python-dotenv>=1.1.0",
    "python-telegram-bot>=22.0",
]

[project.scripts]
bot = "uv run -m make_bot.bot"
